REM sampleCurlWriteCommands.cmd -- Example write operations (POST, PUT, PATCH, DELETE) for this Gilhari service
REM Generated by orm_skyway.py
REM
REM All curl commands below are commented out (REM) to prevent accidental
REM execution. To use a command, remove the REM prefix on the curl line
REM and replace placeholder values with real ones.
REM Each command WILL modify data in your database.
REM For read-only (GET) operations, use sampleCurlCommands.cmd instead.
REM
SET BASE_URL=http://localhost:80/gilhari/v1

REM --- Customers ---

REM POST: Insert a new Customers object
REM curl.exe -s -X POST %BASE_URL%/Customers -H "Content-Type: application/json" -d "{\"entity\": {\"Status\": \"sample_value\", \"CustomerID\": \"sample_value\", \"RowId\": 1, \"FirstName\": \"sample_value\", \"LastName\": \"sample_value\", \"Phone\": \"sample_value\", \"Email\": \"sample_value\"}}"

REM PUT: Update a specific Customers object (supply primary key + all attributes)
REM curl.exe -s -X PUT %BASE_URL%/Customers/updateEntity -H "Content-Type: application/json" -d "{\"entity\": {\"Status\": \"sample_value\", \"CustomerID\": \"sample_value\", \"RowId\": 1, \"FirstName\": \"sample_value\", \"LastName\": \"sample_value\", \"Phone\": \"sample_value\", \"Email\": \"sample_value\"}}"

REM PATCH: Bulk-update Customers objects matching a filter (returns count of updated objects)
REM curl.exe -s -X PATCH "%BASE_URL%/Customers?filter=RowId=1" -H "Content-Type: application/json" -d "{\"newValues\": [\"Status\", \"sample_value\"]}"

REM DELETE: Delete Customers objects matching a filter
REM curl.exe -s -X DELETE "%BASE_URL%/Customers?filter=RowId=1"

