REM Sample curl commands for the Gilhari microservice.
REM Generated by orm_skyway.py
REM
REM GET commands use deep=true (includes related objects) and maxObjects=5.
REM Use deep=false to exclude related objects (useful for complex object graphs).
REM Remove maxObjects to retrieve all qualifying objects,
REM or change it to a different value (-1 to get all qualifying objects).
REM
REM Responses are recorded in curl.log.
REM
REM You may optionally specify a port as the first argument:
REM   sampleCurlCommands 8899
IF %1.==. GOTO DefaultPort
SET port=%1
GOTO Proceed
:DefaultPort
SET port=80
GOTO Proceed
:Proceed

REM Truncate curl.log at the start so it does not grow across runs
echo. > curl.log

echo ** BEGIN OUTPUT ** >> curl.log
echo. >> curl.log

REM -- Health check --
echo ** Health check >> curl.log
curl.exe -s "http://localhost:%port%/gilhari/v1/health/check" | python -m json.tool >> curl.log
echo. >> curl.log

REM -- Object model summary (plain text response, not JSON) --
echo ** Object model summary >> curl.log
curl.exe -s "http://localhost:%port%/gilhari/v1/getObjectModelSummary/now" >> curl.log
echo. >> curl.log

REM -- GET Customers objects - deep (includes related objects, up to 5) --
echo ** GET Customers objects (deep) >> curl.log
curl.exe -s -X GET "http://localhost:%port%/gilhari/v1/Customers?deep=true&maxObjects=5" -H "Content-Type: application/json" | python -m json.tool >> curl.log
echo. >> curl.log

REM -- GET Customers objects - shallow (excludes related objects, up to 5) --
echo ** GET Customers objects (shallow) >> curl.log
curl.exe -s -X GET "http://localhost:%port%/gilhari/v1/Customers?deep=false&maxObjects=5" -H "Content-Type: application/json" | python -m json.tool >> curl.log
echo. >> curl.log

echo ** END OUTPUT ** >> curl.log
echo. >> curl.log
type curl.log
