#!/bin/bash
# sampleCurlWriteCommands.sh — Example write operations (POST, PUT, PATCH, DELETE) for this Gilhari service
# Generated by orm_skyway.py
#
# All curl commands below are commented out (#) to prevent accidental
# execution. To use a command, remove the # prefix on the curl line
# and replace placeholder values with real ones.
# Each command WILL modify data in your database.
# For read-only (GET) operations, use sampleCurlCommands.sh instead.
#
BASE_URL="http://localhost:80/gilhari/v1"

# --- Customers ---

# POST: Insert a new Customers object
# curl -s -X POST "$BASE_URL/Customers" -H "Content-Type: application/json" -d '{"entity": {"Status": "sample_value", "CustomerID": "sample_value", "RowId": 1, "FirstName": "sample_value", "LastName": "sample_value", "Phone": "sample_value", "Email": "sample_value"}}'

# PUT: Update a specific Customers object (supply primary key + all attributes)
# curl -s -X PUT "$BASE_URL/Customers/updateEntity" -H "Content-Type: application/json" -d '{"entity": {"Status": "sample_value", "CustomerID": "sample_value", "RowId": 1, "FirstName": "sample_value", "LastName": "sample_value", "Phone": "sample_value", "Email": "sample_value"}}'

# PATCH: Bulk-update Customers objects matching a filter (returns count of updated objects)
# curl -s -X PATCH "$BASE_URL/Customers?filter=RowId=1" -H "Content-Type: application/json" -d '{"newValues": ["Status", "sample_value"]}'

# DELETE: Delete Customers objects matching a filter
# curl -s -X DELETE "$BASE_URL/Customers?filter=RowId=1"

